<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-KJC6B92" failures="2" tests="2" name="Test(failed)(failed)(failed)" time="0.074" errors="0" timestamp="2024-04-14T10:28:56 IST">
  <testcase classname="pack1.InclusionExclusion" name="TestCase3" time="0.009">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at pack1.InclusionExclusion.TestCase3(InclusionExclusion.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TestCase3 -->
  <testcase classname="pack1.InclusionExclusion" name="TestCase4" time="0.003">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at pack1.InclusionExclusion.TestCase4(InclusionExclusion.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TestCase4 -->
  <testcase classname="pack1.InclusionExclusion" name="TestCase5" time="0.0">
    <ignored/>
  </testcase> <!-- TestCase5 -->
  <testcase classname="pack1.InclusionExclusion" name="TestCase6" time="0.0">
    <ignored/>
  </testcase> <!-- TestCase6 -->
</testsuite> <!-- Test(failed)(failed)(failed) -->
